version: "3.7"

services:
  web:
    image: dockerhub.azk8s.cn/charescape/web:1.0.0
    volumes:
      - ./nginx/vhosts:/usr/local/nginx/vhosts
      - ./nginx/vlogs:/usr/local/nginx/vlogs
      - ./nginx/vconfs:/usr/local/nginx/vconfs
      - ./nginx/vcerts:/usr/local/nginx/vcerts
    ports:
      - "80:80"
      - "443:443"
      - "9000:9000"
    networks:
      - web
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "20"

networks:
  web:
    driver: bridge
