name: Zii-CI

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:
  build:
    name: On ubuntu-latest
    if: "contains(github.event.head_commit.message, 'do ci')"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Docker Build
        run: docker build -t charescape/web:4.0.0 .

      - name: Docker Login
        run: echo "${{ secrets.DOCHUB_PASSWORD }}" | docker login --username ${{ secrets.DOCHUB_USERNAME }} --password-stdin

      - name: Docker Push
        run: docker push charescape/web:4.0.0
