name: Ci

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]


jobs:
  hello:
    name: "hello on ubuntu-22.04"
    if: "contains(github.event.head_commit.message, 'build hello')"

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Docker Build
        run: docker build -f ./dockerfiles/charescape__hello/Dockerfile -t charescape/hello:$GITHUB_RUN_ID .

      - name: Docker Images
        run: docker image ls

      - name: Docker Login
        run: echo "${{ secrets.DOCHUB_PASSWORD }}" | docker login --username ${{ secrets.DOCHUB_USERNAME }} --password-stdin

      - name: Docker Push
        run: docker push charescape/hello:$GITHUB_RUN_ID

#      - name: Build Test
#        run: docker run -i --stop-timeout 10 charescape/hello:$GITHUB_RUN_ID


  web:
    name: web on ubuntu-22.04
    if: "contains(github.event.head_commit.message, 'build web')"

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Build image
        run: docker build -f ./dockerfiles/charescape__web/Dockerfile -t charescape/web:6.0.0 .

      - name: List images
        run: docker image ls

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCHUB_PASSWORD }}" | docker login --username ${{ secrets.DOCHUB_USERNAME }} --password-stdin

      - name: Push image
        run: docker push charescape/web:6.0.0
