name: Zii-CI

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:
  job0:
    name: job0 ON ubuntu-20.04
    if: "contains(github.event.head_commit.message, 'do job0')"

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Docker Build
        run: docker build -f ./dockerfiles/charescape__hello/Dockerfile -t charescape/hello:$GITHUB_RUN_ID .

      - name: Docker Images
        run: docker image ls

      - name: Docker Login
        run: echo "${{ secrets.DOCHUB_PASSWORD }}" | docker login --username ${{ secrets.DOCHUB_USERNAME }} --password-stdin

      - name: Docker Push
        run: docker push charescape/hello:$GITHUB_RUN_ID

#      - name: Build Test
#        run: docker run -i --stop-timeout 10 charescape/hello:$GITHUB_RUN_ID


  job1:
    name: job1 ON ubuntu-20.04
    if: "contains(github.event.head_commit.message, 'do job1')"

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build -f ./dockerfiles/charescape__web/Dockerfile -t charescape/web:4.2.0 .

      - name: List images
        run: docker image ls

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCHUB_PASSWORD }}" | docker login --username ${{ secrets.DOCHUB_USERNAME }} --password-stdin

      - name: Push image
        run: docker push charescape/web:4.2.0
