name: ci2

on:
  push:

jobs:
  build:
    name: Build on ubuntu-24.04
    if: "contains(github.event.head_commit.message, 'release ubuntu24-php84-mysql84.rv6')"

    runs-on: ubuntu-24.04

    env:
      GIT_MSG: ${{ github.event.head_commit.message }}

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.x"

      - name: Check os env
        run: |
          localectl status
          cat /proc/cpuinfo
          free -m

      - run: php src/ubuntu24-php84-mysql84/lite.php

      - name: Build image
        run: docker build -f src/ubuntu24-php84-mysql84/Dockerfile -t charescape/web:ubuntu24-php84-mysql84.rv6 .

      - run: docker image ls

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCHUB_PASSWORD }}" | docker login --username ${{ secrets.DOCHUB_USERNAME }} --password-stdin

      - name: Push image
        run: docker push charescape/web:ubuntu24-php84-mysql84.rv6
