name: ci2

on:
  push:
    branches: [ php81 ]

  pull_request:
    branches: [ php81 ]


jobs:
  build_image:
    name: build image on ubuntu-22.04

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: check os env
        run: |
          localectl status

      - name: build image
        run: docker build -f ./dockerfiles/charescape__web/Dockerfile -t charescape/web:ubuntu20-php80-mysql80.rv0 .

      - name: list images
        run: docker image ls
