name: ci2

on:
  push:
    branches: [ ubuntu22-php81-mysql80 ]

  pull_request:
    branches: [ ubuntu22-php81-mysql80 ]


jobs:
  build_image:
    name: build image on ubuntu-22.04
    if: "contains(github.event.head_commit.message, 'release ubuntu22-php81-mysql80.rv0')"

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: check os env
        run: |
          localectl status

      - name: build image
        run: docker build -f ./dockerfiles/charescape__web/Dockerfile -t charescape/web:ubuntu22-php81-mysql80.rv0 .

      - name: list images
        run: docker image ls

      - name: login to dockerhub
        run: echo "${{ secrets.DOCHUB_PASSWORD }}" | docker login --username ${{ secrets.DOCHUB_USERNAME }} --password-stdin

      - name: push image
        run: docker push charescape/web:ubuntu22-php81-mysql80.rv0

  build_lite_image:
    name: build lite image on ubuntu-22.04
    if: "contains(github.event.head_commit.message, 'release ubuntu22-php81.rv0')"

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: check os env
        run: |
          localectl status

      - name: build image
        run: docker build -f ./dockerfiles/charescape__web/lite/Dockerfile -t charescape/web:ubuntu22-php81.rv0 .

      - name: list images
        run: docker image ls

      - name: login to dockerhub
        run: echo "${{ secrets.DOCHUB_PASSWORD }}" | docker login --username ${{ secrets.DOCHUB_USERNAME }} --password-stdin

      - name: push image
        run: docker push charescape/web:ubuntu22-php81.rv0
