name: ci2

on:
  push:
    branches: [ ubuntu22-php82-mysql80 ]

  pull_request:
    branches: [ ubuntu22-php82-mysql80 ]


jobs:
  build_image:
    name: build image on ubuntu-22.04
    if: "contains(github.event.head_commit.message, 'release ubuntu22-php82-mysql80.rv3')"

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: check os env
        run: |
          localectl status
          cat /proc/cpuinfo
          free -m

      - name: build image
        run: docker build -f ./dockerfiles/charescape__web/Dockerfile -t charescape/web:ubuntu22-php82-mysql80.rv3 .

      - name: list images
        run: docker image ls

      - name: login to dockerhub
        run: echo "${{ secrets.DOCHUB_PASSWORD }}" | docker login --username ${{ secrets.DOCHUB_USERNAME }} --password-stdin

      - name: push image
        run: docker push charescape/web:ubuntu22-php82-mysql80.rv3

  build_lite_image:
    name: build lite image on ubuntu-22.04
    if: "contains(github.event.head_commit.message, 'release ubuntu22-php82.rv4')"

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: check os env
        run: |
          localectl status
          cat /proc/cpuinfo
          free -m

      - name: build image
        run: docker build -f ./dockerfiles/charescape__web/lite/Dockerfile -t charescape/web:ubuntu22-php82.rv3 --add-host dbapi.ttt.com:127.0.0.1 --add-host app.yiitest.com:127.0.0.1 --add-host app.laraveltest.com:127.0.0.1 --add-host app.symfonytest.com:127.0.0.1 .

      - name: list images
        run: docker image ls

      - name: login to dockerhub
        run: echo "${{ secrets.DOCHUB_PASSWORD }}" | docker login --username ${{ secrets.DOCHUB_USERNAME }} --password-stdin

      - name: push image
        run: docker push charescape/web:ubuntu22-php82.rv3
